"""baseline: semester timetable schema

Revision ID: 49ba9c05a863
Revises: 
Create Date: 2026-08-27 09:32:26.746286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49ba9c05a863'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_context',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_year', sa.String(length=20), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=False),
    sa.Column('program', sa.String(length=60), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('semester > 0', name='ck_context_semester'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_year', 'semester', 'program', 'department', name='uq_academic_context')
    )
    op.create_table('faculty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('faculty_code', sa.String(length=20), nullable=False),
    sa.Column('department', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_code')
    )
    op.create_table('subject',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=10), nullable=False),
    sa.Column('session_length_hours', sa.Integer(), nullable=False),
    sa.Column('sessions_per_week', sa.Integer(), nullable=False),
    sa.Column('required_lab_type', sa.String(length=40), nullable=True),
    sa.Column('fixed_room_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("type IN ('theory','practical')", name='ck_subject_type'),
    sa.CheckConstraint('session_length_hours BETWEEN 1 AND 3', name='ck_subject_len'),
    sa.CheckConstraint('sessions_per_week >= 1', name='ck_subject_spw'),
    sa.ForeignKeyConstraint(['fixed_room_id'], ['room.id'], name='fk_subject_fixed_room', ondelete='SET NULL', use_alter=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('timeslot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=12), nullable=False),
    sa.Column('day_index', sa.Integer(), nullable=False),
    sa.Column('period_index', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('is_lunch', sa.Boolean(), nullable=False),
    sa.CheckConstraint('day_index BETWEEN 0 AND 6', name='ck_timeslot_day_index'),
    sa.CheckConstraint('period_index >= 0', name='ck_timeslot_period_index'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_index', 'period_index', name='uq_timeslot_day_period')
    )
    op.create_table('faculty_subject',
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('faculty_id', 'subject_id')
    )
    op.create_table('faculty_unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('faculty_id', 'timeslot_id', name='uq_faculty_unavailable_slot')
    )
    op.create_table('room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_number', sa.String(length=30), nullable=False),
    sa.Column('block', sa.String(length=30), nullable=False),
    sa.Column('floor', sa.String(length=20), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('room_type', sa.String(length=10), nullable=False),
    sa.Column('lab_type', sa.String(length=40), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('fixed_subject_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("room_type IN ('theory','lab','faculty')", name='ck_room_type'),
    sa.CheckConstraint('capacity > 0', name='ck_room_capacity'),
    sa.ForeignKeyConstraint(['fixed_subject_id'], ['subject.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_number')
    )
    op.create_table('section',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_context_id', sa.Integer(), nullable=False),
    sa.Column('section_number', sa.String(length=30), nullable=False),
    sa.Column('strength', sa.Integer(), nullable=False),
    sa.CheckConstraint('strength > 0', name='ck_section_strength'),
    sa.ForeignKeyConstraint(['academic_context_id'], ['academic_context.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_context_id', 'section_number', name='uq_section_number_per_context')
    )
    op.create_table('timetable_run',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_context_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('publish_status', sa.String(length=20), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('objective_value', sa.Float(), nullable=True),
    sa.Column('solve_time_seconds', sa.Float(), nullable=True),
    sa.Column('weights_json', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.CheckConstraint("publish_status IN ('DRAFT','VALIDATED','PUBLISHED','ARCHIVED')", name='ck_run_publish_status'),
    sa.ForeignKeyConstraint(['academic_context_id'], ['academic_context.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_context_id', 'version', name='uq_run_version_per_context')
    )
    op.create_table('assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['timetable_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_assignment_faculty_id'), ['faculty_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_room_id'), ['room_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_run_id'), ['run_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_assignment_section_id'), ['section_id'], unique=False)

    op.create_table('room_unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('room_id', 'timeslot_id', name='uq_room_unavailable_slot')
    )
    op.create_table('section_subject',
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('section_id', 'subject_id')
    )
    op.create_table('section_subject_assignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('academic_context_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('room_id', sa.Integer(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['academic_context_id'], ['academic_context.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculty.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('academic_context_id', 'section_id', 'subject_id', name='uq_section_subject_assignment')
    )
    op.create_table('section_unavailability',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslot.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('section_id', 'timeslot_id', name='uq_section_unavailable_slot')
    )
    op.create_table('subject_allowed_room',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['room.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subject_id', 'room_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subject_allowed_room')
    op.drop_table('section_unavailability')
    op.drop_table('section_subject_assignment')
    op.drop_table('section_subject')
    op.drop_table('room_unavailability')
    with op.batch_alter_table('assignment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_assignment_section_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_run_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_room_id'))
        batch_op.drop_index(batch_op.f('ix_assignment_faculty_id'))

    op.drop_table('assignment')
    op.drop_table('timetable_run')
    op.drop_table('section')
    op.drop_table('room')
    op.drop_table('faculty_unavailability')
    op.drop_table('faculty_subject')
    op.drop_table('timeslot')
    op.drop_table('subject')
    op.drop_table('faculty')
    op.drop_table('academic_context')
    # ### end Alembic commands ###
