"""Phase 6: change_history audit table

Revision ID: c3a4030b454d
Revises: 49ba9c05a863
Create Date: 2026-08-27 23:10:19.860816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3a4030b454d'
down_revision: Union[str, Sequence[str], None] = '49ba9c05a863'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('change_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('section_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=20), nullable=False),
    sa.Column('old_value', sa.String(length=300), nullable=False),
    sa.Column('new_value', sa.String(length=300), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=True),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("change_type IN ('move','room','faculty','lock','unlock')", name='ck_change_history_type'),
    sa.ForeignKeyConstraint(['run_id'], ['timetable_run.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['section_id'], ['section.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('change_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_change_history_run_id'), ['run_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('change_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_change_history_run_id'))

    op.drop_table('change_history')
    # ### end Alembic commands ###
